### ISSUE TITLE
Extra src and destination IP

### ISSUE THREAD

**Issue by wolfman2g1** [noktork/Graylog-CISCO-ASA-Extractor#1]
I've been trying to follow what you've done without success, I'm trying to extract the src and destination ip address, can you please provide some guidance ?

**Comment by noktork** [comment]
You have to create a separate input, I recommend you use a NON-standard port like 1514 as an example. The under that input choose manage.

Here is where you create the input:

![image](https://cloud.githubusercontent.com/assets/12167408/26075495/c5604e7c-39b5-11e7-9515-ee40feb50f83.png)

Klick the "Manage extractor" button for the Raw input you just created.
Since is a new input you should NOT have any extractor, you now need to import my JSON extractor:

![image](https://cloud.githubusercontent.com/assets/12167408/26075624/3ae75a14-39b6-11e7-88cc-02467cf6c553.png)

It's under actions, just paste the complete JSON code into the import dialog window.
Sorry for the delay in my answer.

Good luck!
